### ISSUE TITLE
Dodanie 4-tego servo do węzła dynamixel_servos

### ISSUE THREAD

**Issue by luki193** [LRMPUT/OpenHandNode#5]
# dodajcie 4 servo, żeby działało
 zmiana w pliku *.h liczb serv na 4 nic nie dała, chyba  że coś źle podłączyliśmy, ale pozostałe 3 śmigały elegancko ;)

**Comment by kcwian** [comment]
Oprócz zmiany liczby serw w pliku _servo_control.h_,  trzeba jeszcze zmienić ID czwartego serwa na następne z kolei, czyli 24. Najlepiej to zrobić programem [R+ Manager 2.0](http://en.robotis.com/BlueAD/board.php?bbs_id=downloads&mode=view&bbs_no=1152559&page=1&key=&keyword=&sort=&scate=).
