### ISSUE TITLE
Missing header files

### ISSUE THREAD

**Issue by dominikbelter** [LRMPUT/OpenHandNode#8]
Brakuje w repozytorium plików:
contr_to_ros.h
ros_to_contr.h
s2ros.h
ros2s.h
Znajdziecie jeszcze czas na ich dodanie do repozytorium? 
Będę też wdzięczny za przesłanie filmu nagranego podczas prezentacji.

**Comment by gkmita** [comment]
https://drive.google.com/file/d/13E7TMP8rAdiRtQ9t7MJdFHqk8kXi9w8c/view?usp=sharing

Link do filmów które nagrałem.

**Comment by luki193** [comment]
Nagłowki zostały dodane do repozytorium

**Comment by dominikbelter** [comment]
Dziękuję, umieściłem film na YouTube i na stronie readme repozytorium.
